In [1]:
import pandas as pd
df = pd.read_csv("REFUSAL_ENTRY_2014-October2023.csv", encoding='iso-8859-3')

In [2]:
df_sample = df.sample(int(df.shape[0]*.3))

In [3]:
df.shape[0]*.20

32776.6

In [4]:
df_tmp = pd.get_dummies(df.REFUSAL_CHARGES.str.split(',').explode())[-3:]

In [5]:
df_tmp.to_csv("tmp_example.csv")

In [6]:
from sklearn.preprocessing import MultiLabelBinarizer

In [7]:
mlb = MultiLabelBinarizer()
mlb_t = mlb.fit_transform(df_sample.REFUSAL_CHARGES.str.split(','))

In [8]:
mlb_t

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [9]:
mlb.classes_

array([' 11', ' 115', ' 117', ' 118', ' 126', ' 157', ' 16', ' 160',
       ' 178', ' 179', ' 181', ' 185', ' 186', ' 197', ' 198', ' 2000',
       ' 2020', ' 2040', ' 2080', ' 2120', ' 2160', ' 218', ' 2200',
       ' 223', ' 2240', ' 2280', ' 2300', ' 231', ' 235', ' 2360', ' 237',
       ' 238', ' 2380', ' 241', ' 2460', ' 2480', ' 249', ' 251', ' 253',
       ' 254', ' 256', ' 258', ' 2580', ' 260', ' 262', ' 2640', ' 265',
       ' 2680', ' 27', ' 2720', ' 274', ' 276', ' 278', ' 2780', ' 280',
       ' 2800', ' 281', ' 2860', ' 288', ' 2880', ' 290', ' 2900', ' 292',
       ' 2940', ' 295', ' 2960', ' 297', ' 300', ' 3000', ' 3020', ' 304',
       ' 3040', ' 306', ' 308', ' 3081', ' 309', ' 310', ' 312', ' 3120',
       ' 313', ' 3140', ' 315', ' 3160', ' 3161', ' 318', ' 319', ' 320',
       ' 3200', ' 321', ' 3220', ' 324', ' 3240', ' 325', ' 3260', ' 328',
       ' 3280', ' 329', ' 330', ' 3300', ' 331', ' 332', ' 3320', ' 333',
       ' 3340', ' 335', ' 336', ' 3361', ' 3362', ' 337', ' 3380', ' 339',
       ' 3400', ' 341', ' 342', ' 3421', ' 3422', ' 343', ' 344', ' 3480',
       ' 3500', ' 3560', ' 3600', ' 3621', ' 3641', ' 3681', ' 3701',
       ' 3721', ' 3724', ' 3725', ' 3741', ' 3781', ' 3801', ' 3821',
       ' 3841', ' 3843', ' 3844', ' 3845', ' 3846', ' 3847', ' 3851',
       ' 3852', ' 3854', ' 3862', ' 3863', ' 3864', ' 3865', ' 3870',
       ' 3871', ' 3872', ' 3873', ' 3878', ' 3879', ' 3880', ' 3881',
       ' 3883', ' 3885', ' 3886', ' 3894', ' 3895', ' 3896', ' 3898',
       ' 3900', ' 3902', ' 3905', ' 469', ' 47', ' 471', ' 472', ' 473',
       ' 474', ' 475', ' 476', ' 477', ' 479', ' 48', ' 482', ' 483',
       ' 484', ' 488', ' 508', ' 509', ' 55', ' 62', ' 64', ' 71', ' 72',
       ' 73', ' 75', ' 78', ' 82', ' 83', ' 84', ' 9', '11', '115', '117',
       '118', '126', '152', '157', '16', '160', '170', '171', '175',
       '178', '179', '181', '186', '197', '198', '2000', '2020', '2040',
       '2060', '2080', '2120', '2160', '218', '2200', '2201', '223',
       '2280', '2300', '231', '235', '2360', '237', '238', '2380', '241',
       '2420', '245', '2460', '2461', '2480', '249', '251', '253', '254',
       '255', '256', '258', '2580', '260', '262', '2640', '265', '27',
       '274', '276', '278', '2780', '280', '2800', '281', '286', '2860',
       '288', '2880', '290', '2900', '292', '295', '2960', '297', '2981',
       '299', '300', '3000', '304', '3040', '306', '308', '3081', '309',
       '310', '312', '3120', '313', '314', '3140', '315', '3160', '318',
       '3180', '319', '320', '321', '3220', '324', '3240', '325', '3260',
       '328', '3280', '329', '330', '3300', '331', '3320', '333', '3340',
       '335', '336', '3361', '337', '3380', '3400', '341', '342', '3421',
       '3422', '343', '344', '3460', '3480', '3500', '3520', '3560',
       '3580', '3600', '3621', '3641', '3701', '3721', '3724', '3725',
       '3741', '3761', '3781', '3821', '3841', '3842', '3845', '3846',
       '3847', '3851', '3852', '3854', '3860', '3862', '3864', '3865',
       '3873', '3874', '3875', '3878', '3881', '3885', '3886', '3887',
       '3888', '3889', '3891', '3897', '3898', '3900', '469', '47', '471',
       '472', '473', '474', '475', '476', '477', '479', '48', '480',
       '482', '483', '484', '488', '508', '55', '62', '64', '71', '72',
       '73', '75', '78', '82', '83', '84', '9'], dtype=object)

In [10]:
df_mlb_subsample = pd.DataFrame(mlb_t)

In [11]:
df_mlb_subsample

,0,1,2,3,4,5,6,7,8,9,...,377,378,379,380,381,382,383,384,385,386
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49159,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49160,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49161,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
49162,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
49163,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0